### ISSUE TITLE
Tracking issue for next release series

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/utils#1070]
This is a tracking issue for the next set of breaking releases which are currently under development on the master branch.

These are somewhat interdependent on https://github.com/RustCrypto/traits/issues/1571

- [ ] `block-buffer` v0.11 (depends on `crypto-common` v0.2)
- [ ] `block-padding` v0.4 (depends on `hybrid-array` v0.2)
- [ ] `dbl` v0.4 (depends on `hybrid-array` v0.2)
- [ ] `inout` v0.2 (depends on `block-padding` v0.4)

**Comment by tarcieri** [comment]
@newpavlov I'm wondering if we can cut final releases of some or all of these now and start getting the ball rolling on stable releases

**Comment by newpavlov** [comment]
One potentially unresolved problem with `block-buffer` is efficient serialization of eager buffers (current version of `digest` serializes eager buffer into block size + 1 byte, while block size would be sufficient). Right now we have inherent serialization methods, but unfortunately they are a bit hard to combine with implementation of `SerializableState`. I will try to work on it during this weekend.

I also thought about moving buffer implementation used by the stream cipher wrapper to `block-buffer`, since it's the only place in `cipher` which uses `unsafe`.

Another change which I would like to introduce is a minor change to the blobby format as noted [here](https://github.com/RustCrypto/utils/pull/1187#discussion_r2161935470).

Finally, regarding `dbl`, we probably should make a decision on #1077. It does not prevent us from cutting a release and deprecating it later, but I think it would be better to not cut a potentially quickly deprecated release.

Otherwise, I don't have objections to cutting the releases.

**Comment by tarcieri** [comment]
@newpavlov where are we on this now?

**Comment by newpavlov** [comment]
I thought about cutting releases after fixing https://github.com/RustCrypto/AEADs/issues/716.

**Comment by newpavlov** [comment]
I opened #1217 after inspecting the `block-padding` code for one last time before creating a release PR.

Another potential change for `block-buffer`: constitfication of methods. It could be useful for https://github.com/RustCrypto/hashes/issues/288, e.g. if we decide to provide free-standing hashing `const fn`s in our crates. Unfortunately, it would involve a rework of the `Lazy/Eager` traits since we do not have `const impl`, so it requires some experimentation.

**Comment by newpavlov** [comment]
Unfortunately, it's not possible to constify the `BlockBuffer::digest_blocks` method on the current stable Rust. It accepts a generic closure, so we need at least `~const` bounds. There is also a problem with const destruction, but it can be worked around by passing a reference to closure.

**Comment by newpavlov** [comment]
#1221 is not a blocker, but it would be nice to fix as part of the v0.4.0 release.

**Comment by baloo** [comment]
I know you already said it was not a blocker, but it looks ready.

Is there anything left before a release of block-padding other than https://github.com/RustCrypto/utils/pull/1222 ?
It looks like that's the last thing and it should unblock every other crate here?

**Comment by newpavlov** [comment]
Before releasing `block-buffer` (the only remaining crate in the list) I would like to resolve https://github.com/RustCrypto/traits/issues/1808 since it may involve changing implementation of `ReadBuffer`.

**Comment by newpavlov** [comment]
block-buffer v0.11.0 is released in #1246.

**Comment by baloo** [comment]
Thank you folks for all the work toward those releases!
