### ISSUE TITLE
crypto-bigint: feature wishlist tracking ticket

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/utils#453]
This is a ticket for tracking desired new features for `crypto-bigint` and which algorithms should be used in order to implement particular features.

Unless otherwise stated, these features are implied to be for the `UInt` type.

- [ ] multiplication algorithms
  - [x] "grade school"
  - [ ] Karatsuba
  - [ ] Montgomery
- [ ] modpow
- [ ] sqrt
- [ ] bitwise operations
  - [ ] shift
  - [ ] rotate
  - [ ] XOR
  - [ ] (request additional bitwise ops in comments)
- [ ] fields mod n (i.e. wrapper newtypes for `UInt`)
- [ ] constant-time division
- [ ] `subtle` comparisons
  - [x]  `ConstantTimeEq`
  - [ ] `ConstantTimeGreater`
  - [ ] `ConstantTimeLess`
- [ ] GCD (algorithms listed below)
  - [safegcd](https://gcd.cr.yp.to/safegcd-20190413.pdf)
  - [safegcd-bounds](https://github.com/sipa/safegcd-bounds)
- [ ] CRT (algorithms listed below)
  - https://eprint.iacr.org/2020/1507
- [ ] SIMD backends
  - [ ] AVX2
  - [ ] NEON

**Comment by mikelodder7** [comment]
- Prime generation 
- Random < n
- Least common multiple
- Negative numbers
- Inverse (available if gcd exists but nice convenience)

**Comment by tarcieri** [comment]
@mikelodder7 added to the list

random < n implemented in #508. Will cut a release with that fairly soon.

Re: signed integers, yes that's definitely planned but not on this list yet, so thanks. Tentatively the idea is composing in terms of a `UInt` using two's complement.

**Comment by mikelodder7** [comment]
How about bit tests? Check if bit at position `i` is set or cleared?

**Comment by tarcieri** [comment]
@mikelodder7 what kind of API are you looking for there?

Would a `Choice` suffice, or are you looking for a secret-dependent/vartime API?

**Comment by mikelodder7** [comment]
Choice will suffice. Vartime not necessary.

**Comment by ggutoski** [comment]
Fast generation of safe primes would be great for RSA applications.

**Comment by mikelodder7** [comment]
It’s also great for applications that require groups of unknown order based on prime factoring like accumulator, paillier, camenisch-shoup verifiable encryption

**Comment by complexspaces** [comment]
I'd like to add a +1 for implementing`modpow`. It's useful in older protocols such as SRP.

**Comment by Sc00bz** [comment]
Doing a "better random < n" with https://github.com/apple/swift/pull/39143 in bigint is expensive compared to correct bigint rejection sampling (see #618). As that requires multiplication of the modulus and a random number about 128 bits larger than the modulus. Basically that's O(N^2) vs O(N).

**Comment by dignifiedquire** [comment]
> To be clear @dignifiedquire tried to add generic mulmod in #510 but it was buggy so we backed it out.

I'll get there, soon (TM)
