### ISSUE TITLE
hex-literal: v1.0 tracker

### ISSUE THREAD

**Issue by newpavlov** [RustCrypto/utils#814]
`hex-literal` is quite stable, with v0.3.0 being release over two years ago. So I think we can start to consider v1.0 release.

Potential changes:
- [x] Bump MSRV to 1.56 and edition to 2021 (Done in v0.4)
- [x] Decide whether we want to forbid comments inside literals or not, as described [here](https://github.com/RustCrypto/utils/issues/813#issuecomment-1286189440) (Done in v0.4)
- [x] Use https://github.com/rust-lang/cargo/issues/9930. It will allow us to bump `hex-literal` edition without breaking downstream builds and maybe incorporate new language features.
- [x] Use inline `const {}` expressions to force const evaluation (MSRV 1.79).
- [ ] Wait for stabilization of `generic_const_exprs` and `adt_const_params`? It would allow us to write:
```rust
fn decode<const DATA: &'static [u8]>() -> [u8; decode_len(DATA)] { ... }
```

**Comment by Nugine** [comment]
It's possible to implement `hex!` macro with const evaluation. See [const_str::hex!](https://docs.rs/const-str/latest/const_str/macro.hex.html).

**Comment by newpavlov** [comment]
Yeah, it [works](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=4fd209f78f8868d7fcf16f895617f962) on Nightly and the code does not look too bad.

But this approach has the following disadvantages:
1) `hex::<"abcdef">()` is... not great. Introducing a wrapper macro partially solves the issue, but ideally we would use [const arguments](https://internals.rust-lang.org/t/pre-rfc-const-function-arguments/6709). Unfortunately, it's highly unlikely that they will be added to the language. :(
2) Error diagnostics are much worse. We can not even panic with message which includes encountered invalid character. With macros we potentially can point the exact place which triggers an error.

**Comment by newpavlov** [comment]
hex-literal v1.0.0 is released!
